### ISSUE TITLE
Finite variable width slider (that scrolls only visible slides), slides should always fill the display area

### ISSUE THREAD

**Issue by dryleaf** [akiran/react-slick#1334]
>I hope this is not a "big ask" but I'm stuck and I love your library as it has helped me a lot in the past.

## Overview
My issue is that I'm trying to adjust the [variable width](https://react-slick.neostack.com/docs/example/variable-width/) slider (in your documentation) in order to be:
1. `finite`
2. `responsive` (to different viewports) (if possible to display as many slides according to viewport width)
3. `scroll only 100% visible slides`
4. slides should fill the `div` display area

### Observations

1. So far, I have managed to make it:
   - `finite`

2. Regarding `responsive`, breakpoints don't work well for `variable width` slides.

3. `scroll only 100% visible slides`, This is very important when it comes to variable viewport width and when using variable width slides.

4. `slides should fill the`**div**`display area`, _finite variable width slides_ when they reach the last slide, even though it was already visible by the previous scroll, the user can still scroll and what is visible is a huge area of blank slides, for example:
![blank slides visible after last slide](https://user-images.githubusercontent.com/16116003/43869254-9a2e5082-9bac-11e8-8c93-602caed61341.png)

## The Code
The issue can be replicated and tested in [code sandbox](https://codesandbox.io/s/983v21ooq4)

> I'm open to hear your expert solutions.

**Comment by diegopamio** [comment]
I've made a fix that would allow the finite variable width slider sliders to always fill the display area, using a new setting. I've added the pull request, not sure if it will be handled soon. In any case, you are free to use my own fork in your package.json: 
`"react-slick": "git+https://git@github.com/diegopamio/react-slick.git", `

But ideally, if you can, also please vote so that the pull request gets attention.

**Comment by dryleaf** [comment]
Thanks. Is there a way I can use your solution in [Code Sandbox](https://codesandbox.io/?from-app=1)?

**Comment by diegopamio** [comment]
According to https://github.com/CompuIves/codesandbox-client/issues/278
you can do that by manually updating the package.json with: 
`"react-slick": "diegopamio/react-slick.git"`

instead of the full uri. I've tried that and it worked for me.

**Comment by diegopamio** [comment]
Yes, it does, but know I'm thinking perhaps that's not needed, as it should work even when slidesToScroll > 1... I can modify that guard.

**Comment by Razum** [comment]
Any progress on this issue?

**Comment by dryleaf** [comment]
My ideal scroller would the one that is:
- finite
- Variable width
- scrolls all 100% visible slides
- with no paddings or centerings

**Comment by diegopamio** [comment]
Done, I've updated the PR to do that.

**Comment by dryleaf** [comment]
I have tested and it doesn't work. And the following test case: fails
- Scrolls all 100% visible slides at a time (irrespective of viewports or screen width)
> This means that if 3 slides are 100% visible, then they should all be scrolled, and so on.
> But your solution always scrolls one slide at time and it can not be changed.

I suggested you test it first with the following code:
- [finite variable width](https://codesandbox.io/s/6l4wpv0q8z)

**Comment by akimy** [comment]
@diegopamio suggestion for this problem solving?
```variableWidth: true```
```infinite: false```,  lead to blank space from the right.

I've just expecting last slide right border to intersect slider right border + partially view left slide.
But in last right position 've blank full size left slide + blank space from the right.

**Comment by leadeg** [comment]
any fixes for spaces on from right?

**Comment by leimonio** [comment]
@akiran 👋  is there any update on this matter? I can still reproduce this issue.

**Comment by babysteps** [comment]
i'm looking for a fix to this as well.  any updates?

**Comment by jota12x** [comment]
> @diegopamio any suggestion for this problem solving?
> `variableWidth: true`
> `infinite: false`, lead to blank space from the right.
> 
> I've just expecting last slide right border to intersect slider right border + partially view left slide.
> But in last right position 've full size left slide + blank space from the right.

I encountered this problem as well.

**Comment by taigfs** [comment]
Me too.

**Comment by p-abasian** [comment]
Same here +1

**Comment by duongthaison98** [comment]
+1

**Comment by dikshantpatodia** [comment]
w.r.t. to above scenario, when variableWidth is true and infinite is false, the below issue also occurs

**Situation:**
- When `variableWidth` is `true`
- Arrows are shown (I need to show the arrows as the content is dynamic and it can overflow the viewport)

**Issue:**
Issue 1: Arrows should be disabled or should not show when all the elements are visible in viewport

Similar issue was found in swiper js, but they have the provision of watching the overflow by a `watchOverflow` prop which is set to true, which takes care of the above issue mentioned.
